name = 'mirror'
license = 'MIT'
licenselink = 'https://github.com/rokuosan/mirror/LICENSE'
description = 'Simple Portfolio for Hugo'

homepage = 'https://github.com/rokuosan/mirror'
demosite = 'https://rokuosan.github.io/mirror/'

[author]
  name = 'rokuosan'
  homepage = 'Your website'
